services:
  client:
    build:
      context: . # Root directory (where the Dockerfile is located)
      dockerfile: Dockerfile # Ensure the correct Dockerfile is used
      target: client
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}' # Frontend will be available on port 3000
    volumes:
      - ./client:/app # Mount the client folder to the container (for live development)
    working_dir: /app
    command: npm start # This will run `npm start` inside the frontend container
    environment:
      - CLIENT_ENV=${CLIENT_ENV} # Takes .env variable for DEV/PROD

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./server:/app
    working_dir: /app
    command: python server.py
    environment:
      - SERVER_ENV=${SERVER_ENV} # Takes .env variable for DEV/PROD
      - MONGO_INITDB_USER=${MONGO_INITDB_USER}
      - MONGO_INITDB_PWD=${MONGO_INITDB_PWD}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - client
      - mongodb
    env_file:
      - .env # Make sure the environment file is loaded

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}' # mongodb will be available on port 27017
    volumes:
      - mongo-data:/data/db
    container_name: Mongo-Container

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: conf # Ensure we build only the conf stage (for copying config files)
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - ./nginx/conf:/etc/nginx/conf # Mount local conf directory to container's /etc/nginx/conf
    environment:
      - NGINX_ENV=${NGINX_ENV}
    depends_on:
      - client
      - server

volumes:
  mongo-data:
